Firefox fix
UTDNebula/skedge pull request #61
Opened 2024-04-11 18:17 UTC by TyHil

Firefox requires requesting host permissions instead of automatically granting them.

This PR opens a prompt to grant permissions on install and every time skedge is opened without correct permissions.

2024-04-15 21:59 UTC, nl32 commented
If the user tries to open the extension and doesn't have host permissions, it will now open the popup and request them. 
Also added styling so the popup uses the right font and button uses `blue-dark`

2024-07-10 01:54 UTC, demonlexe requested changes

2024-07-10 01:54 UTC, demonlexe commented on src/background/index.ts
> +  console.log('hey from install listener');
nit: remove console logs for a merge into main

2024-07-10 01:54 UTC, demonlexe commented on src/tabs/permissions.tsx
> +      <h1 className="">Sk.edge needs permissions to run</h1>
nit: can remove className=""

2024-07-10 01:54 UTC, demonlexe commented on src/popup.tsx
> +    console.log('opening permission request');
remove console logs

2024-07-16 04:41 UTC, demonlexe approved these changes

2024-07-16 18:48 UTC, merged